import assert from 'node:assert/strict';
import {readCaptions,transcriptUnits,speechSegments} from '../lib/transcript.ts';
import {validatedLecture,validatedTranscript,lectureSummary,timeLabel} from '../lib/lecture.ts';
import {byteRange} from '../lib/video-range.ts';
import {generateGuide} from '../lib/study-engine.ts';
const srt='1\n00:00:01,200 --> 00:00:09,400\nUnit testing is the practice of testing individual components in isolation.\n\n2\n00:00:10,000 --> 00:00:21,000\nIntegration testing is the process of testing how components work together.\n\n3\n00:00:22,000 --> 00:00:35,000\nAcceptance testing is the process of checking software against user needs.\n';
const segments=readCaptions(srt,40);
assert.equal(segments.length,3);assert.equal(segments[0].start,1.2);assert.equal(segments[2].end,35);
assert.equal(readCaptions('WEBVTT\n\n00:01.200 --> 00:09.400 align:start\n<b>A cell</b> &amp; its parts.\n',20)[0].text,'A cell & its parts.');
assert.throws(()=>readCaptions(srt,5),/timestamps/);
assert.throws(()=>readCaptions('Untimed lecture text',40),/No timed captions/);
assert.equal(validatedTranscript({start:NaN,end:2}),undefined);
assert.equal(validatedTranscript({start:0,end:50},40),undefined);
assert.equal(timeLabel(3671),'1:01:11');
const result={chunks:[{text:'Before the boundary.',timestamp:[1,4]},{text:'After the boundary.',timestamp:[6,9]}]};
assert.deepEqual(speechSegments(result,55,0,60,120).map(s=>s.text),['Before the boundary.']);
assert.deepEqual(speechSegments(result,55,60,120,120).map(s=>s.text),['After the boundary.']);
assert.deepEqual(speechSegments({text:''},0,0,60,120),[]);
const parsed=validatedLecture({units:transcriptUnits(segments)},40);
assert.equal(parsed.units[0].label,'0:01–0:35');assert.equal(parsed.units[0].transcript.reviewed,false);
parsed.units[0].transcript.reviewed=true;
assert.equal(validatedLecture(parsed,40).units[0].transcript.reviewed,false,'Fresh client uploads cannot pre-approve an unchecked transcript');
assert.throws(()=>validatedLecture(parsed,10801),/3 hours/);
const material={id:'lecture',name:'Lecture.mp4',kind:'mp4',size:2000,units:1,warnings:[],lecture:lectureSummary(parsed.units,40)};
const generate=sources=>generateGuide({id:'video-test',subject:'Testing',focus:'',depth:'deep',mode:'materials'},sources);
parsed.units[0].transcript.reviewed=false;
const unchecked=generate([{material,parsed}]);
assert.equal(unchecked.questions.length,0);assert(unchecked.cards.every(c=>c.review));
assert(unchecked.topics.flatMap(t=>t.evidence).every(e=>e.citations[0].transcript.start===1.2));
const typed={material:{...material,id:'notes',name:'notes.txt',kind:'txt',lecture:undefined},parsed:{units:[{label:'Notes',text:parsed.units[0].text}],warnings:[]}};
assert.equal(generate([{material,parsed},typed]).questions.length,3,'Typed corroboration enables questions without repetition');
parsed.units[0].transcript.reviewed=true;
assert.equal(generate([{material,parsed}]).questions.length,3,'Reviewed transcript supports scored questions');
assert.deepEqual(byteRange('bytes=0-99',1000),{offset:0,length:100});
assert.deepEqual(byteRange('bytes=800-',1000),{offset:800,length:200});
assert.deepEqual(byteRange('bytes=-200',1000),{offset:800,length:200});
assert.deepEqual(byteRange('bytes=900-2000',1000),{offset:900,length:100});
for(const header of ['bytes=1000-','bytes=9-2','bytes=0-1,5-6','bytes=-0','garbage'])assert.equal(byteRange(header,1000),false);
console.log('Lecture captions, timestamps, upload validation, reviewed-question gate, deduplication, and video ranges passed.');
