import assert from 'node:assert/strict';
import {ocrParagraphText,ocrSummary,ocrWarnings,additionalImageText,validatedOcr} from '../lib/ocr-reading.ts';
import { generateGuide, demoGuide, diagnostic, focusTopics, recordPractice, practiceQueue } from '../lib/study-engine.ts';
const empty = () => ({known:[],review:[],answers:{},assessment:{},assessed:false});
const source = (id, text) => ({material:{id,name:id+'.txt',kind:'txt',units:1,size:text.length,warnings:[]},parsed:{warnings:[],units:[{label:'Page 1',text}]}});
const generate = (sources, depth='deep') => generateGuide({id:'test',subject:'Study test',focus:'',depth,mode:'materials'},sources);
const base = 'Cell structure\nThe cell membrane is a selectively permeable barrier that controls movement of substances into and out of the cell.\nThe cytoplasm consists of the cytosol and the structures suspended in it.\nRibosomes are the cellular structures that build proteins from amino acids.';
const overlap=generate([source('slides',base),source('reading',base)]);
const wrapped=ocrParagraphText([['Testing methods'],['Unit testing is the practice of testing individual','components in isolation.'],['Integration testing is the process of testing how','components work together.'],['Acceptance testing is the process of checking software','against user needs.']]);
assert.equal(generate([source('wrapped',wrapped)]).questions.length,3);
assert(generate([source('wrapped',wrapped)]).questions.every(q=>q.explanation.endsWith('.')),'Wrapped scan lines must preserve full definitions in questions');
const spacedScan=[['Unit testing is the practice of testing individual'],['components in isolation.']];
const lineBoxes=[{x0:100,y0:230,x1:900,y1:266},{x0:102,y0:302,x1:540,y1:336}];
assert.equal(ocrParagraphText(spacedScan,lineBoxes),'Unit testing is the practice of testing individual components in isolation.');
assert(ocrParagraphText(spacedScan,[lineBoxes[0],{...lineBoxes[1],x0:1200}]).includes('\n\n'),'Text from a different column must stay separate');
assert(ocrParagraphText(spacedScan,[lineBoxes[0],{...lineBoxes[1],y0:500,y1:534}]).includes('\n\n'),'Separate page paragraphs must not be joined');
const scanned=source('scan',base);
scanned.parsed.units[0].ocr={confidence:65,reviewed:false,images:[{page:1}]};
const uncertainScan=generate([scanned]);
assert.equal(uncertainScan.questions.length,0,'Uncertain image text cannot become a scored question');
assert(uncertainScan.cards.every(c=>c.review),'Uncertain recall cards keep their source-check warning');
assert(uncertainScan.topics.flatMap(t=>t.evidence).every(e=>e.citations[0].ocr.confidence===65),'OCR provenance survives guide creation');
const corroboratedScan=generate([scanned,source('typed',base)]);
assert.equal(corroboratedScan.questions.length,3,'Typed corroboration can support scored questions without repeating the scan');
scanned.parsed.units[0].ocr.reviewed=true;
assert.equal(generate([scanned]).questions.length,3,'Reviewed and corrected image text is eligible for scored questions');
assert.deepEqual(ocrSummary(scanned.parsed.units),{units:1,needsReview:0});
const unknownScan=source('unread',base);unknownScan.parsed.units[0].ocr={confidence:0,reviewed:false,images:[{}]};
assert.equal(generate([unknownScan]).questions.length,0,'Zero confidence never passes the question gate');
assert.equal(ocrWarnings(scanned.parsed.units,['Image text: old warning','Other note']).filter(w=>w.startsWith('Image text:')).length,1);
assert.equal(additionalImageText('A typed heading\nExisting text is kept.','A typed heading\nExisting text is kept.\nA new image sentence.'),'A new image sentence.');
assert.equal(validatedOcr({confidence:NaN,images:[]}),undefined);
assert.deepEqual(validatedOcr({confidence:60,reviewed:false,images:[{path:'../../secret'},{page:1}]}).images,[{page:1}]);
assert.equal(overlap.topics.length,1);
assert.equal(overlap.cards.length,3);
assert.equal(overlap.questions.length,3);
assert.equal(overlap.questions[0].citations.length,2);
for(const q of overlap.questions){assert.equal(new Set(q.options).size,q.options.length);assert(q.citations.every(c=>c.quote===q.explanation&&c.excerpt.includes(c.quote)));}
const differing=generate([source('lecture','Properties\nPressure is measured at 100 kPa in this experiment.\nThe coating is electrically conductive under these conditions.\n'+base),source('handout','Properties\nPressure is measured at 200 kPa in this experiment.\nThe coating is not electrically conductive under these conditions.')]);
assert.equal(differing.builtIn.sourceChecks,4);
assert(!differing.questions.some(q=>/Pressure|coating/i.test(q.options[q.correct])));
assert(differing.cards.find(c=>c.front==='Explain Pressure.').review);
assert(differing.topics.flatMap(t=>t.points).some(p=>p.includes('not electrically')));
const math=generate([source('math','Equations\na = -5 m/s²\na = 5 m/s²\nF = ma\nx < 10\nx > 10')]);
assert.equal(math.topics[0].points.length,5);
assert.equal(math.cards.filter(c=>c.front.includes('Complete this relationship')).length,3);
assert.equal(math.questions.length,0);
assert(math.cards.some(c=>c.back.includes('-5')));
const roles=generate([source('roles','Relationships\nPlants consume oxygen and release carbon dioxide.\nPlants release oxygen and consume carbon dioxide.')]);
assert.equal(roles.topics[0].points.length,2);
const ambiguous=generate([source('ambiguity','Concepts\nAlpha is a standard tool for organizing the work into groups.\nBeta is a standard tool for organizing the work into groups.\nGamma is the original measure of distance between two points.\nDelta is the duration of the experiment under observation.')]);
assert(!ambiguous.questions.some(q=>['Alpha','Beta'].includes(q.options[q.correct])));
const acronym=generate([source('acronym',base+'\nApplication programming interface (API) is a contract that lets software components communicate.'),source('acronym2','Interfaces\nAPI is a contract that lets software components communicate.')]);
assert.equal(acronym.questions.filter(q=>/API|Application programming/.test(q.options[q.correct])).length,1);
const list=generate([source('list','Benefits\n• Flexible\n• Reusable\n• Easy to maintain')]);
assert.equal(list.topics[0].points.length,3);
assert(list.cards[0].back.includes('Flexible'));
const g=demoGuide(),initial=empty();
initial.assessed=true;for(const q of diagnostic(g))initial.assessment[q.id]=q.correct;
assert.equal(focusTopics(g,initial).strong.size,0,'A diagnostic cannot establish whole-topic mastery');
const q=g.questions[0],now=1_000_000;
let p=recordPractice(empty(),q,q.correct,false,now);
assert(focusTopics(g,p,now).weak.has(q.topicId),'A correct guess stays in focus');
assert.equal(p.practice[q.id].streak,0);
p=recordPractice(p,q,q.correct,true,now+600_000);
assert.equal(p.practice[q.id].streak,1);
p=recordPractice(p,q,q.correct,true,now+601_000);
assert.equal(p.practice[q.id].streak,1,'Immediate retries do not count as spaced recall');
p=recordPractice(p,q,q.correct,true,now+1_202_000);
assert.equal(p.practice[q.id].streak,2);
p=recordPractice(p,q,-1,false,now+1_203_000);
assert.equal(p.practice[q.id].streak,0);
assert.equal(practiceQueue(g.questions,p,now+1_203_000)[0].id,q.id);
const quick=generate([source('quick',base+'\nDNA is a molecule that stores hereditary information in the sequence of its bases.')],'quick');
assert.equal(quick.topics[0].points.length,3);
assert.equal(quick.cards.length,4,'Quick overview must not lose the other recall material');
console.log('Study engine: overlap, exact evidence, conflicts, formulas, relational order, ambiguous questions, acronyms, lists, adaptive review, and quick-mode coverage passed.');

const { studyCoverage } = await import('../lib/study-coverage.ts');
const { validatedReadingReport } = await import('../lib/reading-report.ts');
const application=generate([source('methods','Testing methods\nUnit testing is the practice of testing individual components in isolation.\nIntegration testing is the process of testing how components work together.\nAcceptance testing is the process of checking software against user needs.\nLoad testing is the process of measuring behavior under a specified workload.')]);
assert(application.questions.length>=3);
assert(application.questions.every(q=>q.kind==='application'&&q.evidenceIds.length===1));
assert.equal(new Set(application.questions.map(q=>q.id)).size,application.questions.length);
const causal=generate([source('causes','Why things happen\nThe metal rod expands because its particles move farther apart during heating.\nThe alarm sounds because the smoke detector has sensed smoke particles.\nThe lamp illuminates because electric current flows through its circuit.')]);
assert.equal(causal.questions.filter(q=>q.kind==='cause').length,3);
for(const q of causal.questions){assert(q.explanation.includes(q.options[q.correct]));assert(q.citations.every(c=>c.quote===q.explanation));}
const comparison=generate([source('comparison','Testing comparison\nUnit testing checks individual components, whereas integration testing checks interactions between components.')]);
assert.equal(comparison.questions.length,1);
assert.equal(comparison.questions[0].kind,'comparison');
assert.equal(comparison.questions[0].options[comparison.questions[0].correct],'Unit testing checks individual components; integration testing checks interactions between components.');
assert(new Set(comparison.questions[0].options).size===4);
let cp=empty();let cov=studyCoverage(application,cp,now);
assert.equal(cov.checked,0);assert.equal(cov.unchecked,4);
cp={...cp,known:application.cards.map(c=>c.id)};
assert.equal(studyCoverage(application,cp,now).checked,0,'Self-rated recall cannot inflate scored coverage');
cp.assessment[application.questions[0].id]=application.questions[0].correct;
cov=studyCoverage(application,cp,now);assert.equal(cov.checked,1);assert.equal(cov.unchecked,3);
cp=recordPractice(cp,application.questions[0],application.questions[0].correct,false,now);
cov=studyCoverage(application,cp,now);assert.equal(cov.review,1);assert.equal(cov.ready,0);
const reading=source('reading',base);reading.parsed.units.push({label:'Page 2',text:'7'});reading.parsed.reading={totalUnits:3,unreadable:[{label:'Page 3',reason:'Image-only page.'}]};
const rg=generate([reading]);const rc=studyCoverage(rg,empty(),now).sources[0];
assert.equal(rc.reading.totalUnits,3);assert.equal(rc.reading.readableLabels.length,2);assert.equal(rc.reading.unreadable.length,1);assert.equal(rc.reading.notRepresented[0].label,'Page 2');assert.equal(rc.representedUnits,1);
const unknown=studyCoverage(overlap,empty(),now).sources[0];assert.equal(unknown.reading.totalUnits,undefined,'Legacy total counts remain unknown, not guessed');
assert.deepEqual(validatedReadingReport(reading.parsed.reading,['Page 1','Page 2']),reading.parsed.reading);
assert.equal(validatedReadingReport({totalUnits:3,unreadable:[{label:'Page 1',reason:'Duplicate'}]},['Page 1','Page 2']),undefined);
const sourceStates=studyCoverage(differing,empty(),now);assert.equal(sourceStates.sourceChecks,4);
const mc=studyCoverage(math,empty(),now);assert.equal(mc.checked,0);assert(mc.recall>0);
console.log('Coverage and deeper questions: applications, causes, comparisons, precise passage coverage, uncertain answers, recall-only material, reading gaps, and legacy uploads passed.');
