import assert from 'node:assert/strict';
import {demoGuide,generateGuide,recordPractice} from '../lib/study-engine.ts';
import {emptyProgress} from '../lib/study-types.ts';
import {migrateProgress,validatedExtras,sourceSequences,objectiveMatches,priorityCards} from '../lib/study-tools.ts';
import {validatedSession} from '../lib/study-session.ts';
import {startExam,finishExam} from '../lib/exam.ts';
const g=demoGuide(),c=g.cards[0],q=g.questions[0],now=Date.now();
let p=recordPractice({...emptyProgress(),known:[c.id],recall:{[c.id]:{draft:'My explanation',revealed:true,checked:[0]}}},q,q.correct,false,now);
assert.equal(p.practice[q.id].streak,0,'Assisted or uncertain recall does not advance mastery');assert.equal(p.mistakes[q.id].misses,1);
p.mistakes[q.id].note='I confused two terms';
const next=structuredClone(g);next.createdAt=g.createdAt+10;next.cards[0].id='new-card';next.questions[0].id='new-question';next.questions[0].options.reverse();next.questions[0].correct=next.questions[0].options.indexOf(q.options[q.correct]);
let migrated=migrateProgress(g,next,p);assert(migrated.known.includes('new-card'));assert.equal(migrated.answers['new-question'],next.questions[0].correct);assert.equal(migrated.mistakes['new-question'].note,'I confused two terms');assert.equal(migrated.recall['new-card'].draft,'My explanation');
next.cards[0].back+=' A corrected fact.';next.questions[0].explanation+=' Changed evidence.';migrated=migrateProgress(g,next,p);assert(!migrated.known.includes('new-card'));assert(!migrated.practice['new-question']);assert(!migrated.recall['new-card']);
const cite={sourceId:'notes',name:'Notes',label:'Page 1',excerpt:''};
assert.equal(sourceSequences('Protocol steps\n1. Prepare the first sample.\n2. Measure the sample mass.\n3. Record the sample mass.',cite).length,1);
assert.equal(sourceSequences('Favorite instruments\n1. Balance for weighing.\n2. Beaker for liquids.',cite).length,0,'Numbered lists without a process heading are not ordered processes');
assert.equal(sourceSequences('Protocol steps\n1. Prepare the first sample.\n3. Record the mass.',cite).length,0,'Missing steps cannot create a sequence');
const src={material:{id:'source',name:'Notes',kind:'txt',units:1,size:1,warnings:[]},parsed:{units:[{label:'Page 1',text:'Protocol steps\n1. Prepare the first sample.\n2. Measure the sample mass.\n3. Record the sample mass.'}],warnings:[]}};
const seq=generateGuide({id:'steps',subject:'Lab',focus:'',depth:'deep',mode:'materials'},[src,{...src,material:{...src.material,id:'other'}}]);assert.equal(seq.sequences.length,1);assert.equal(seq.sequences[0].citations.length,2,'Overlapping sequences share a single practice item');
assert.equal(objectiveMatches('Explain quantum entanglement',g).length,0);assert(objectiveMatches('Explain the cell membrane',g).length>0);
assert(priorityCards(g,{...emptyProgress(),review:[g.cards.at(-1).id]})[0].id===g.cards.at(-1).id);
const s=validatedSession({tab:'tools',tool:'plan',quizzes:{full:{questionIds:[q.id,'not-real'],index:5,selected:99,hints:{[q.id]:99}}}},g);assert.equal(s.tab,'tools');assert.equal(s.tool,'plan');assert.equal(s.quizzes.full.hints[q.id],2);assert.equal(s.quizzes.full.index,0);
const cleaned=validatedExtras({recall:{[c.id]:{draft:'x',checked:[0,0,-1,500]},bad:{}},diagrams:[{id:'d',assetId:'asset',labels:[{id:'l',text:'cell',x:2,y:-1,w:20,h:0}],answers:{l:'CELL',bad:'bad'}}],examHistory:[{id:'1',total:4,correct:99,topics:[]},{id:'1',total:4,correct:99}],objectives:[{text:'Explain cell structure',status:'bad',evidenceIds:['bad']}],focusSession:{cardIds:['bad']},studyPlan:{examDate:'bad',dailyMinutes:900}},g);
assert.deepEqual(cleaned.recall[c.id].checked,[0]);assert.equal(cleaned.diagrams[0].labels[0].x,.98);assert.equal(cleaned.examHistory.length,1);assert.equal(cleaned.examHistory[0].correct,4);assert.equal(cleaned.objectives[0].status,'unchecked');assert.equal(cleaned.focusSession,undefined);assert.equal(cleaned.studyPlan.dailyMinutes,180);
const exam=startExam(g.questions,5,10,now);exam.answers[exam.questionIds[0]]=g.questions.find(q=>q.id===exam.questionIds[0]).correct;
const finished=finishExam({...emptyProgress(),session:{view:'guide',tab:'exam',full:false,exam}},g.questions,now+1000,g.topics);assert.equal(finished.examHistory.length,1);assert.equal(finished.examHistory[0].correct,1);assert(finished.examHistory[0].topics.some(t=>g.topics.some(x=>x.title===t.title)));assert.deepEqual(finishExam(finished,g.questions,now+2000,g.topics),finished,'Repeated finish cannot duplicate history or practice');
assert.equal(migrateProgress(g,next,finished).examHistory.length,1,'History survives material updates');
console.log('Study tools: content-based progress migration, option remapping, review history, validated saved state, ordered-source guards, source deduplication, objectives, and priority plans passed.');
const compareGuide=generateGuide({id:'compare',subject:'Testing',focus:'',depth:'deep',mode:'materials'},[{...src,parsed:{units:[{label:'Notes',text:'Definitions\nVerification is the process of checking specified requirements.\nValidation is the process of checking actual user needs.'}],warnings:[]}}]);
assert.equal(objectiveMatches('Compare verification and validation',compareGuide).length,2,'Comparison objectives can match two separate definitions');
const {reviewSheetHtml}=await import('../lib/review-sheet.ts');
const html=reviewSheetHtml({...g,subject:'<script>alert(1)</script>'},[{...c,back:'x < y & z > 0'}]);assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'));assert(html.includes('x &lt; y &amp; z &gt; 0'));
