'use client';
import{useEffect,useState}from'react';
import{Timer,ArrowRight,ChevronLeft,Flag,Check,BookOpen,RotateCw}from'lucide-react';
import{Button}from'@/components/ui/button';
import{Checkbox}from'@/components/ui/checkbox';
import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from'@/components/ui/select';
import{AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction}from'@/components/ui/alert-dialog';
import{Sources}from'./practice';
import{startExam,finishExam,examQuestions}from'@/lib/exam';
import{withSession}from'@/lib/study-session';
import type{Citation,ExamSession,ProgressData,Question,Topic}from'@/lib/study-types';
export function Exam({questions,topics,progress,onChange,onCite,onPractice}:{questions:Question[];topics:Topic[];progress:ProgressData;onChange:(p:ProgressData)=>void;onCite:(c:Citation)=>void;onPractice:()=>void}){
 const[count,setCount]=useState(20),[minutes,setMinutes]=useState(20),[now,setNow]=useState(Date.now),[confirm,setConfirm]=useState(false);
 const exam=progress.session?.exam,done=exam?.finishedAt!==undefined,available=examQuestions(questions,50,()=>.5).length;
 const pool=exam?.questionIds.map(id=>questions.find(q=>q.id===id)!).filter(Boolean)||[],q=pool[exam?.index||0];
 const remaining=exam?Math.max(0,Math.ceil((exam.endsAt-now)/1000)):0;
 const change=(patch:Partial<ExamSession>)=>{if(exam&&!done&&Date.now()<exam.endsAt)onChange(withSession(progress,{exam:{...exam,...patch}}));};
 useEffect(()=>{if(!exam||done)return;setNow(Date.now());const timer=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(timer);},[exam?.startedAt,done]);
 useEffect(()=>{if(exam&&!done&&now>=exam.endsAt){setConfirm(false);onChange(finishExam(progress,questions,now,topics));}},[now,exam,done,progress,questions,onChange]);
 if(!exam)return <div className="practice-panel exam-setup"><div className="practice-toolbar"><div><h2><Timer size={23}/>Timed exam</h2><p>Mix topics from your full guide. Answers and source explanations appear after you finish.</p></div></div>{available?<><div className="exam-settings"><div><label htmlFor="exam-count">Questions</label><Select value={String(count)} onValueChange={v=>setCount(Number(v))}><SelectTrigger id="exam-count"><SelectValue/></SelectTrigger><SelectContent>{[10,20,30,50].map(n=><SelectItem value={String(n)} key={n}>{n} questions</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="exam-minutes">Time limit</label><Select value={String(minutes)} onValueChange={v=>setMinutes(Number(v))}><SelectTrigger id="exam-minutes"><SelectValue/></SelectTrigger><SelectContent>{[5,10,20,30,60].map(n=><SelectItem value={String(n)} key={n}>{n} minutes</SelectItem>)}</SelectContent></Select></div></div><div className="exam-ready"><strong>{Math.min(count,available)} questions · {minutes} minutes</strong><p>{available<count?`Your guide has ${available} distinct scored questions. All will be included. `:''}Flag guesses or uncertain answers. The timer keeps running if you leave or reload; saved answers return when you reopen this guide.</p></div><Button onClick={()=>{const next=startExam(questions,count,minutes);setNow(next.startedAt);onChange(withSession(progress,{exam:next}));}}><Timer size={16}/>Start timed exam<ArrowRight size={16}/></Button></>:<div className="empty-state"><BookOpen size={30}/><h2>No scored questions available yet.</h2><p>Review your lecture or image text and rebuild the guide. You can still study its source passages and flashcards.</p></div>}</div>;
 const correct=pool.filter(q=>exam.answers[q.id]===q.correct).length,review=pool.filter(q=>exam.answers[q.id]!==q.correct||exam.flagged.includes(q.id)),answered=pool.filter(q=>exam.answers[q.id]!==undefined).length;
 if(done)return <div className="practice-panel"><div className="exam-result-heading"><div className="score-orb">{pool.length?Math.round(correct/pool.length*100):0}%</div><div><h2>Your exam review</h2><p>{correct} of {pool.length} correct · {pool.length-answered} unanswered · {exam.flagged.length} flagged</p><p>{exam.finishedAt===exam.endsAt?'The time limit ended your exam.':'Exam submitted.'} Missed and uncertain concepts now lead your adaptive practice.</p></div></div><div className="result-actions">{!!review.length&&<Button onClick={onPractice}>Practice missed &amp; unsure<ArrowRight size={16}/></Button>}<Button variant="outline" onClick={()=>onChange(withSession(progress,{exam:undefined}))}><RotateCw size={16}/>New exam</Button></div>{review.length?<div className="exam-review-list">{review.map((q,i)=><article className="exam-review-item" key={q.id}><span className="card-label">{i+1} · {exam.answers[q.id]===undefined?'UNANSWERED':exam.answers[q.id]!==q.correct?'TO REVISIT':'CORRECT, BUT UNSURE'}</span><h3>{q.prompt}</h3><p><strong>Your answer:</strong> {q.options[exam.answers[q.id]]||'No answer'}</p><p className="exam-correct"><Check size={16}/><strong>Correct answer:</strong> {q.options[q.correct]}</p><p>{q.explanation}</p><Sources citations={q.citations} onClick={onCite}/></article>)}</div>:<div className="comparison-clear"><Check size={18}/>Every answer was correct with no uncertainty flagged. Try again later to check retention.</div>}</div>;
 if(!q)return null;
 return <div className="practice-panel"><div className="practice-toolbar"><div><h2>Timed exam</h2><p>Question {exam.index+1} of {pool.length} · {answered} answered</p></div><div className={'exam-clock'+(remaining<60?' urgent':'')} role="timer" aria-label="Time remaining"><Timer size={19}/>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</div></div><nav className="exam-navigator" aria-label="Exam questions">{pool.map((item,i)=><Button key={item.id} variant="outline" size="icon-sm" aria-label={`Question ${i+1}${exam.answers[item.id]!==undefined?', answered':''}${exam.flagged.includes(item.id)?', flagged':''}`} aria-current={i===exam.index?'step':undefined} className={(i===exam.index?'current ':'')+(exam.answers[item.id]!==undefined?'answered ':'')+(exam.flagged.includes(item.id)?'flagged':'')} disabled={!remaining} onClick={()=>change({index:i})}>{i+1}{exam.flagged.includes(item.id)&&<span className="exam-flag-dot"/>}</Button>)}</nav><div className="quiz-card"><h2 className="question-passage">{q.prompt}</h2><div className="quiz-options">{q.options.map((option,i)=><button key={i} className={'quiz-option'+(exam.answers[q.id]===i?' selected':'')} aria-pressed={exam.answers[q.id]===i} disabled={!remaining} onClick={()=>change({answers:{...exam.answers,[q.id]:i}})}><span className="option-letter">{String.fromCharCode(65+i)}</span>{option}</button>)}</div><label className="exam-uncertain"><Checkbox checked={exam.flagged.includes(q.id)} disabled={!remaining} onCheckedChange={v=>change({flagged:v===true?[...new Set([...exam.flagged,q.id])]:exam.flagged.filter(id=>id!==q.id)})}/><Flag size={16}/><span>I’m unsure — include this in my review</span></label><div className="exam-controls"><Button variant="outline" disabled={exam.index===0||!remaining} onClick={()=>change({index:exam.index-1})}><ChevronLeft size={16}/>Previous</Button>{exam.index<pool.length-1?<Button disabled={!remaining} onClick={()=>change({index:exam.index+1})}>Next<ArrowRight size={16}/></Button>:<Button disabled={!remaining} onClick={()=>setConfirm(true)}>Finish exam<Check size={16}/></Button>}</div></div><Button className="exam-finish" variant="ghost" disabled={!remaining} onClick={()=>setConfirm(true)}>Finish and see results</Button><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Finish this exam?</AlertDialogTitle><AlertDialogDescription>{pool.length-answered?`${pool.length-answered} questions are unanswered. They count as missed. `:''}You can review the answers and return to uncertain topics afterward.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep working</AlertDialogCancel><AlertDialogAction onClick={()=>onChange(finishExam(progress,questions,Date.now(),topics))}>Submit exam</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
