'use client';
import{useRef,useState}from'react';
import{Clapperboard,Upload,FileText,AlertCircle}from'lucide-react';
import{Button}from'@/components/ui/button';
import{Checkbox}from'@/components/ui/checkbox';
import{Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle}from'@/components/ui/dialog';
import{VIDEO_ACCEPT,MAX_VIDEO_BYTES}from'@/lib/lecture';
export function LectureUpload({onClose,onAdd,initialScreen=false}:{onClose:()=>void;onAdd:(file:File,captions?:File,screen?:boolean)=>void;initialScreen?:boolean}){
 const[screen,setScreen]=useState(initialScreen);
 const[file,setFile]=useState<File>(),[captions,setCaptions]=useState<File>(),[error,setError]=useState(''),videoInput=useRef<HTMLInputElement>(null),captionInput=useRef<HTMLInputElement>(null);
 function add(){if(!file){setError('Choose a lecture video first.');return;}if(file.size>MAX_VIDEO_BYTES){setError('Choose a video up to 1 GB. Split longer recordings into parts.');return;}if(captions&&captions.size>2_000_000){setError('Choose a caption file under 2 MB.');return;}onAdd(file,captions,screen);onClose();}
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="lecture-upload-dialog"><DialogHeader><DialogTitle><Clapperboard size={21}/>Add a lecture video</DialogTitle><DialogDescription>Use your teacher’s spoken explanations alongside your slides and readings.</DialogDescription></DialogHeader><div className="lecture-upload-choice"><strong>1. Choose your recording</strong><Button variant="outline" onClick={()=>videoInput.current?.click()}><Upload size={16}/>{file?file.name:'Choose lecture video'}</Button><input ref={videoInput} aria-label="Lecture video" type="file" accept={VIDEO_ACCEPT} className="sr-only" onChange={e=>{setFile(e.target.files?.[0]);setError('');}}/><p>MP4, MOV, M4V, or WebM · up to 1 GB and 3 hours</p></div><div className="lecture-upload-choice"><strong>2. Add captions if you have them <span>(optional)</span></strong><Button variant="outline" onClick={()=>captionInput.current?.click()}><FileText size={16}/>{captions?captions.name:'Choose SRT or VTT captions'}</Button><input ref={captionInput} aria-label="Lecture captions" type="file" accept=".srt,.vtt" className="sr-only" onChange={e=>setCaptions(e.target.files?.[0])}/>{captions&&<Button variant="link" onClick={()=>{setCaptions(undefined);if(captionInput.current)captionInput.current.value='';}}>Use automatic transcription instead</Button>}<p>Matching captions skip automatic transcription. You can correct either transcript before studying.</p></div><label className="lecture-screen-option"><Checkbox checked={screen} onCheckedChange={v=>setScreen(v===true)}/><span><strong>Read text shown in the video</strong><small>English printed text · checks every 5 seconds, up to 480 changed frames. Takes longer. Brief slides and diagrams may be missed.</small></span></label><div className="lecture-info"><strong>{captions?'Your captions keep their timestamps.':'Automatic English transcription · no API credits'}</strong><p>{captions?'Your video and transcript will be saved in your private study space.':'The speech reader downloads on first use and runs on your device. Longer lectures take time; keep this tab open until the upload finishes. Chrome or Edge works best.'}</p><p>Completed sections and upload parts are saved. After closing this tab, choose the same video, captions, and screen-text option to resume. Upload parts expire after 24 hours; your extracted text remains saved.</p></div>{error&&<div className="alert" role="alert"><AlertCircle size={17}/>{error}</div>}<DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={add} disabled={!file}>{captions?'Add lecture with captions':'Transcribe & add lecture'}</Button></DialogFooter></DialogContent></Dialog>;
}
