'use client';
import{useEffect,useRef,useState}from'react';
import{CalendarDays,Timer,Play,Pause,Download,Printer,Upload,ArrowRight}from'lucide-react';
import{Button}from'@/components/ui/button';import{Input}from'@/components/ui/input';import{Textarea}from'@/components/ui/textarea';
import{Sources}from'./practice';import type{ToolProps}from'./understanding-tools';import{objectiveMatches,priorityCards}from'@/lib/study-tools';import type{FocusSession}from'@/lib/study-tools';
import{extract,ACCEPT}from'@/lib/extract';
import{reviewSheetHtml}from'@/lib/review-sheet';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export function ExamChecklist({guide,progress,onChange,onCite}:ToolProps){
 const[text,setText]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),input=useRef<HTMLInputElement>(null);const objectives=progress.objectives||[];
 function add(raw:string,source=progress.objectiveSource){const lines=raw.split(/\r?\n/).map(s=>s.trim().replace(/^[-•]\s*/, '')).filter(Boolean),seen=new Set(objectives.map(o=>o.text.toLowerCase()));const added=lines.filter(s=>{if(seen.has(s.toLowerCase()))return false;seen.add(s.toLowerCase());return true;}).slice(0,150-objectives.length).map((s,i)=>({id:'objective-'+Date.now()+'-'+i,text:s.slice(0,1000),status:'unchecked' as const,evidenceIds:[]}));onChange({...progress,objectives:[...objectives,...added],objectiveSource:source});setText('');setStatus(added.length+' objectives added. Review the wording and remove headings or unrelated lines.');}
 async function upload(file:File){setError('');try{setStatus('Reading your review sheet…');const parsed=await extract(file,setStatus);const data=new FormData();data.set('file',file);data.set('parsed',JSON.stringify(parsed));const r=await fetch('/api/materials',{method:'POST',body:data}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);add(parsed.units.map(u=>u.text).join('\n'),file.name);if(parsed.warnings.length||parsed.units.some(u=>u.ocr&&!u.ocr.reviewed))setStatus('Review the imported wording, especially image text and formulas. '+parsed.warnings.join(' '));}catch(e){setError(e instanceof Error?e.message:'Could not read the review sheet.');setStatus('');}}
 return <><div className="tool-heading"><h2>Check your exam coverage</h2><p>Add your teacher’s learning objectives or review sheet. Match each requirement to your guide, then confirm it yourself.</p></div><div className="tool-card"><label className="field-label">Objectives, one per line<Textarea rows={4} value={text} maxLength={50000} onChange={e=>setText(e.target.value)} placeholder="Explain the stages of…&#10;Compare…&#10;Calculate…"/></label><div className="compact-buttons"><Button disabled={!text.trim()||objectives.length>=150} onClick={()=>add(text)}>Add objectives</Button><Button variant="outline" onClick={()=>input.current?.click()}><Upload size={16}/>Upload review sheet</Button><input className="sr-only" ref={input} type="file" aria-label="Upload exam objectives" accept={ACCEPT} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f);}}/></div><p className="muted small">Up to 150 objectives. Imported sheets are saved with your materials. They are compared against this guide, not counted as proof that it covers itself.</p>{status&&<p role="status">{status}</p>}{error&&<p className="alert" role="alert">{error}</p>}</div><p><strong>{objectives.filter(o=>o.status==='covered').length}/{objectives.length}</strong> confirmed covered · {objectives.filter(o=>o.status==='practice').length} need practice{progress.objectiveSource&&<> · From {progress.objectiveSource}</>}</p>{objectives.map(o=>{const matches=objectiveMatches(o.text,guide);return <article className="tool-card" key={o.id}><label className="field-label">Objective<Input value={o.text} maxLength={1000} onChange={e=>onChange({...progress,objectives:objectives.map(x=>x.id===o.id?{...x,text:e.target.value,status:'unchecked',evidenceIds:[]}:x)})}/></label><p className={matches.length?'muted':'coverage-gap'}>{matches.length?'Possible source matches — check that they answer the full objective.':'No close passage found. Add relevant material or identify the missing topic.'}</p>{matches.map((e,i)=><div className="objective-match" key={e.id||i}><p>{e.text}</p><Sources citations={e.citations} onClick={onCite}/></div>)}<div className="compact-buttons"><select aria-label={'Coverage status for '+o.text} value={o.status} onChange={e=>onChange({...progress,objectives:objectives.map(x=>x.id===o.id?{...x,status:e.target.value as typeof o.status,evidenceIds:matches.flatMap(e=>e.id?[e.id]:[])}:x)})}><option value="unchecked">Not checked yet</option><option value="covered">I confirmed coverage</option><option value="practice">Needs material / practice</option></select><Button variant="ghost" onClick={()=>onChange({...progress,objectives:objectives.filter(x=>x.id!==o.id)})}>Remove objective</Button></div></article>;})}</>;
}
function sessionFor(ids:string[],minutes:number):FocusSession{return{phase:'study',cardIds:ids,completed:[],index:0,revealed:false,minutes,endsAt:Date.now()+minutes*60000};}
export function DailyPlan({guide,progress,onChange}:ToolProps){const p=progress.studyPlan||{examDate:'',dailyMinutes:20,completedDays:[]},cards=priorityCards(guide,progress),budget=Math.max(1,Math.floor(p.dailyMinutes/2)),day=today(),days=p.examDate?Math.ceil((new Date(p.examDate+'T00:00:00').getTime()-new Date(day+'T00:00:00').getTime())/86400000)+1:0;const change=(patch:Partial<typeof p>)=>onChange({...progress,studyPlan:{...p,...patch}});
 const start=()=>onChange({...progress,focusSession:sessionFor(cards.slice(0,budget).map(c=>c.id),p.dailyMinutes),session:{view:'guide',tab:'tools',full:false,...progress.session,tool:'focus'}});
 return <><div className="tool-heading"><h2>A plan for your next exam</h2><p>Your weak, due, and unreviewed concepts come first. The plan adjusts as you practice.</p></div><div className="tool-columns"><label className="field-label">Exam date<Input type="date" value={p.examDate} min={day} onInput={e=>change({examDate:e.currentTarget.value})} onChange={e=>change({examDate:e.target.value})} onBlur={e=>{if(e.target.value!==p.examDate)change({examDate:e.target.value});}}/></label><label className="field-label">Minutes per day<Input type="number" min={5} max={180} value={p.dailyMinutes} onChange={e=>change({dailyMinutes:Math.max(5,Math.min(180,Number(e.target.value)||5))})}/></label></div>{p.examDate&&days<1&&<p className="alert">This exam date has passed. Choose a new date to plan the remaining reviews.</p>}<article className="tool-card"><h3><CalendarDays size={19}/>Today · {p.dailyMinutes} minutes</h3><p>{Math.min(cards.length,budget)} concepts · about two minutes per concept, adjustable to your pace.</p><ol>{cards.slice(0,budget).map(c=><li key={c.id}>{c.front}</li>)}</ol>{cards.length?<Button onClick={start}><Play size={16}/>Start today’s focus session</Button>:<p>Review uncertain source text to unlock study cards.</p>}<label className="check-line"><input type="checkbox" checked={p.completedDays.includes(day)} onChange={e=>change({completedDays:e.target.checked?[...new Set([...p.completedDays,day])]:p.completedDays.filter(d=>d!==day)})}/>Mark today’s plan complete</label></article>{days>0&&<><h3>{days} {days===1?'day':'days'} until your exam, including today</h3><p>{cards.length>days*budget?'Your current time budget may not cover every concept once. Increase your daily time or prioritize the most important objectives.':'Leave time for another recall attempt after the first pass.'} These are planning estimates, not a prediction of your exam score.</p><div className="plan-days">{Array.from({length:Math.min(days,14)},(_,i)=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+i);const items=cards.slice(i*budget,(i+1)*budget);return <article key={i}><strong>{d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</strong><span>{p.dailyMinutes} min</span><p>{i===0?'Today’s priorities':items.length?items.map(c=>c.front.replace(/^Explain /,'')).join(' · '):'Revisit due concepts and check your exam objectives.'}</p></article>;})}</div>{days>14&&<p className="muted">Showing the next 14 days. Future priorities update with your results.</p>}</>}</>;
}
export function FocusSessionTool({guide,progress,onChange,onCite}:ToolProps){const[minutes,setMinutes]=useState(15),[count,setCount]=useState(5),[now,setNow]=useState(Date.now);const s=progress.focusSession,cards=priorityCards(guide,progress),remaining=s?(s.remainingMs??Math.max(0,s.endsAt-now)):0,card=s?guide.cards.find(c=>c.id===s.cardIds[s.index]):undefined;
 const change=(patch:Partial<FocusSession>)=>s&&onChange({...progress,focusSession:{...s,...patch}});
 useEffect(()=>{if(!s||s.phase==='done'||s.remainingMs!==undefined)return;setNow(Date.now());const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[s?.phase,s?.endsAt,s?.remainingMs]);
 useEffect(()=>{if(s&&s.phase==='break'&&s.remainingMs===undefined&&remaining<=0)change({phase:'done'});},[remaining,s?.phase]);
 const complete=(needsReview:boolean)=>{if(!s||!card)return;const completed=[...new Set([...s.completed,card.id])],index=s.index+1;onChange({...progress,review:needsReview?[...new Set([...progress.review,card.id])]:progress.review,focusSession:{...s,completed,index:Math.min(index,s.cardIds.length-1),revealed:false,...(completed.length===s.cardIds.length?{remainingMs:0}:{})}});};
 return <><div className="tool-heading"><h2>One focused study session</h2><p>Choose a small goal, work through it, then take a five-minute break.</p></div>{!s||s.phase==='done'?<div className="tool-card">{s?.phase==='done'&&<p role="status">Session complete. You reviewed {s.completed.length} concepts and finished your break.</p>}<div className="tool-columns"><label className="field-label">Session length<select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}>{[10,15,25,40].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><label className="field-label">Concept goal<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,5,10,15].map(n=><option key={n} value={n}>{n} concepts</option>)}</select></label></div><Button disabled={!cards.length} onClick={()=>{setNow(Date.now());onChange({...progress,focusSession:sessionFor(cards.slice(0,count).map(c=>c.id),minutes)});}}><Play size={16}/>Start focused session</Button></div>:<article className="tool-card"><div className="focus-session-top"><h3>{s.phase==='break'?'Take a break':'Your study goal'}</h3><span className="exam-clock" role="timer"><Timer size={20}/>{Math.floor(remaining/60000)}:{String(Math.floor(remaining/1000)%60).padStart(2,'0')}</span></div><p>{s.completed.length}/{s.cardIds.length} concepts reviewed{ s.remainingMs!==undefined&&remaining>0?' · Paused':''}</p>{s.phase==='study'&&remaining>0&&card?<><h3>{card.front}</h3>{s.revealed?<><p className="question-passage">{card.back}</p><Sources citations={card.citations} onClick={onCite}/><div className="compact-buttons"><Button variant="outline" onClick={()=>complete(true)}>Needs more practice</Button><Button onClick={()=>complete(false)}>Reviewed · next<ArrowRight size={15}/></Button></div></>:<Button variant="outline" onClick={()=>change({revealed:true})}>Reveal source answer</Button>}</>:s.phase==='study'?<><h3>{s.completed.length===s.cardIds.length?'You reached your goal.':'Time for a break.'}</h3><p>You reviewed {s.completed.length} concepts. Unfinished concepts remain available for your next session.</p><Button onClick={()=>{setNow(Date.now());change({phase:'break',endsAt:Date.now()+300000,remainingMs:undefined});}}>Start five-minute break</Button></>:<p>Step away, stretch, or get some water. Your progress is saved.</p>}<div className="compact-buttons focus-controls">{remaining>0&&<Button variant="outline" onClick={()=>{setNow(Date.now());change(s.remainingMs===undefined?{remainingMs:Math.max(0,s.endsAt-Date.now())}:{endsAt:Date.now()+s.remainingMs,remainingMs:undefined});}}>{s.remainingMs===undefined?<><Pause size={15}/>Pause</>:<><Play size={15}/>Resume</>}</Button>}<Button variant="ghost" onClick={()=>onChange({...progress,focusSession:undefined})}>End session</Button></div></article>}</>;
}
export function ReviewSheet({guide,progress,onCite}:ToolProps){const[scope,setScope]=useState('focus'),[limit,setLimit]=useState(15),ordered=priorityCards(guide,progress),cards=(scope==='all'?guide.cards:ordered).slice(0,limit);
 function download(){const html=reviewSheetHtml(guide,cards);const url=URL.createObjectURL(new Blob([html],{type:'text/html'})),a=document.createElement('a');a.href=url;a.download='studyroom-review.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><div className="tool-heading no-print"><h2>Your take-away review sheet</h2><p>Keep definitions, formulas, source references, and priority concepts together for offline study.</p></div><div className="compact-buttons no-print"><select aria-label="Review sheet topics" value={scope} onChange={e=>setScope(e.target.value)}><option value="focus">Weak and due concepts first</option><option value="all">Full guide order</option></select><select aria-label="Review sheet size" value={limit} onChange={e=>setLimit(Number(e.target.value))}>{[10,15,25,50,100].map(n=><option value={n} key={n}>Up to {n} concepts</option>)}</select><Button variant="outline" onClick={()=>window.print()}><Printer size={16}/>Print / Save PDF</Button>{guide.mode==='example'?<Button variant="outline" onClick={download}><Download size={16}/>Download review sheet</Button>:<Button asChild variant="outline"><a href={'/api/guides/'+guide.id+'/review-sheet?scope='+scope+'&limit='+limit} download="studyroom-review.html"><Download size={16}/>Download review sheet</a></Button>}</div><section className="print-review" id="print-review"><h1>{guide.subject}</h1><p>{cards.length} concepts · {new Date().toLocaleDateString()}</p>{cards.map(c=><article className="review-print-card" key={c.id}><h2>{c.front}</h2><p className="question-passage">{c.back}</p>{c.review&&<p className="source-check">Check source: {c.review}</p>}<div className="no-print"><Sources citations={c.citations} onClick={onCite}/></div><p className="print-citations">{c.citations.map(s=>s.name+' · '+s.label).join(' / ')}</p></article>)}</section></>;
}
