'use client';
import{useState}from'react';
import{AlertTriangle,ArrowUpRight,CheckCheck,LoaderCircle,ScanSearch}from'lucide-react';
import{Button}from'@/components/ui/button';
import type{PassageMatch}from'@/lib/source-matching';
type Report={items:PassageMatch[];files:number;sourceKey?:string;passages:number;checked:number;skipped:number;limited:boolean;revision:string};
const reason=(value:string)=>value==='numbers'?'Different numbers':value==='negation'?'Check a negative statement':'Possible misheard term';
export function TranscriptComparison({id,index,sourceIds,revision,disabled}:{id:string;index:number;sourceIds:string[];revision:string;disabled:boolean}){
 const[report,setReport]=useState<Report>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function check(){setBusy(true);setError('');try{const response=await fetch('/api/materials/'+id+'/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceIds})}),data=await response.json() as Report&{error?:string};if(!response.ok)throw new Error(data.error||'The comparison could not finish.');setReport({...data,sourceKey:[...sourceIds].sort().join('|')});}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}
 const stale=report&&(report.revision!==revision||report.sourceKey!==[...sourceIds].sort().join('|')),items=!stale?report?.items.filter(item=>item.unitIndex===index)||[]:[];
 return <section className="transcript-comparison"><div className="comparison-heading"><div><h3><ScanSearch size={18}/>Compare with class material</h3><p>{sourceIds.length?'Check this lecture against the documents selected for your guide.':'Add slides, PDFs, or notes to this guide to compare them with the lecture.'}</p></div><Button variant="outline" size="sm" disabled={busy||disabled||!sourceIds.length} onClick={()=>void check()}>{busy?<LoaderCircle size={15} className="spinner"/>:<ScanSearch size={15}/>} {busy?'Comparing…':report?'Check again':'Check transcript'}</Button></div>{error&&<p className="file-error" role="alert">{error}</p>}{report&&<><p className="ocr-note">{stale?'Your selected sources or transcript changed. Check again to refresh the comparisons.':`${report.files} ${report.files===1?'file':'files'} · ${report.passages} reference passages · ${report.items.length} possible ${report.items.length===1?'difference':'differences'} across the lecture.`}{report.limited?' This is a partial comparison; not all passages were checked.':''}{report.skipped?' Some selected files could not be used.':''}</p>{!stale&&!items.length&&<p className="comparison-clear"><CheckCheck size={15}/>{report.passages?'No close wording differences were detected in this section. This does not verify every claim.':'No suitable reference passages were available.'}</p>}{items.map((item,i)=><article className="comparison-item" key={i}><strong><AlertTriangle size={16}/>{item.reasons.map(reason).join(' · ')}</strong><div className="comparison-quotes"><div><span>Lecture transcript</span><p>{item.quote}</p></div><div><span>{item.reference.name} · {item.reference.label}</span><p>{item.reference.quote}</p><a href={'/api/materials/'+item.reference.sourceId} download>Open original<ArrowUpRight size={13}/></a></div></div><p className="ocr-note">Listen and compare the context before editing. Either source could contain an error.</p></article>)}</>}</section>;
}
