import{env}from 'cloudflare:workers';
import type{Material,Parsed}from './study-types';
export function storage(){if(!env.DB||!env.BUCKET)throw new Error('Your study space is temporarily unavailable. Please try again; your input is still here.');return{db:env.DB,bucket:env.BUCKET};}
export class RequestError extends Error{constructor(message:string,public status=400,public code?:string){super(message);}}
export function fail(e:unknown){console.error('Studyroom request failed',e);return Response.json({error:e instanceof RequestError?e.message:'Something went wrong. Please try again. Your materials are still saved.',...(e instanceof RequestError&&e.code?{code:e.code}:{})},{status:e instanceof RequestError?e.status:503,headers:{'Cache-Control':'no-store'}});}
export function origin(request:Request){const o=request.headers.get('Origin');if((o&&o!==new URL(request.url).origin)||request.headers.get('Sec-Fetch-Site')==='cross-site')throw new RequestError('Open Studyroom and try again.',403);}
export function validId(v:unknown){if(typeof v!=='string'||! /^[a-zA-Z0-9-]{1,80}$/.test(v))throw new RequestError('Invalid item.');return v;}
export async function json(request:Request){if(Number(request.headers.get('content-length')||0)>2_000_000)throw new RequestError('This request is too large.',413);const s=await request.text();if(s.length>2_000_000)throw new RequestError('This request is too large.',413);try{return JSON.parse(s);}catch{throw new RequestError('The request could not be read.');}}
export async function generalSource(subject:string):Promise<{material:Material;parsed:Parsed}>{try{const params=new URLSearchParams({action:'query',format:'json',formatversion:'2',generator:'search',gsrsearch:subject,gsrlimit:'1',prop:'extracts|info',inprop:'url',explaintext:'1',exsectionformat:'wiki',exlimit:'1'});const res=await fetch('https://en.wikipedia.org/w/api.php?'+params,{headers:{'User-Agent':'Studyroom/1.0 (educational study guide)'},signal:AbortSignal.timeout(20000)});if(!res.ok)throw new RequestError('The general topic source is unavailable right now. Add class files or paste notes to continue.',503);const d=await res.json()as{query?:{pages?:{pageid:number;title:string;extract?:string;fullurl?:string}[]}};const p=d.query?.pages?.[0];if(!p?.extract||p.extract.length<150)throw new RequestError('No useful overview was found. Try a specific subject or add class materials.');const units:Parsed['units']=[];let title='Introduction';for(const block of p.extract.split(/(^={2,6} .+? ={2,6}$)/m)){if(/^==/.test(block)){title=block.replace(/^=+\s*|\s*=+$/g,'').trim();continue;}if(/^(references|external links|further reading|see also|notes|bibliography)$/i.test(title))continue;if(block.trim().length>80)units.push({label:title,text:title+'\n'+block.trim()});}return{material:{id:'wiki-'+p.pageid,name:p.title+' — Wikipedia',kind:'web',size:p.extract.length,units:units.length,warnings:[],url:p.fullurl||'https://en.wikipedia.org/wiki/'+encodeURIComponent(p.title)},parsed:{units,warnings:[]}};}catch(e){if(e instanceof RequestError)throw e;throw new RequestError('The general topic source could not be reached. Add class files or paste notes to continue.',503);}}
